{% set version = "20200309" %}

package:
  name: iota2
  version: {{ version }}

source:
  git_url: https://framagit.org/iota2-project/iota2.git
  git_rev: v20200309
  

build:
    skip: True  # [not linux]
    number: 1

requirements:
  host:
    - python=3.6
    - numpy>=1.14.6,<2.0a0
    - otb=6.7
    - config=0.4.2
    - dill
    - scipy
    - matplotlib
    - pandas
    - scikit-image
    - mpi4py=3.0.0=py36_openmpi_3
    - openmpi=3.1.3

  run:
    - python=3.6
    - numpy>=1.14.6,<2.0a0
    - otb=6.7
    - config=0.4.2
    - dill
    - scipy
    - matplotlib=3.0.2
    - pandas
    - geopandas
    - scikit-image
    - grass=7.7
    - mpi4py=3.0.0=py36_openmpi_3
    - openmpi=3.1.3
    - scikit-learn
    - rasterio
    - boto3
    - yapf
    - pylint
    - mypy

extra:
  recipe-maintainers:
    - CESBIO
